import { Alegreya_Sans_SC } from "next/font/google";
import "./globals.scss";
import Header from "./_components/Header/Header";

const Alegreya = Alegreya_Sans_SC({
  subsets: ["latin"],
  weight: ["400", "500", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Alegreya.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
