import { Alegreya_Sans_SC } from "next/font/google";
import "./_styles/globals.scss";
import Header from "./_components/Header/Header";
import Providers from "./_components/Providers";
const Alegreya = Alegreya_Sans_SC({
  subsets: ["latin"],
  weight: ["400", "500", "800"],
});

export const metadata = {
  title: "Holidaze",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={Alegreya.className}>
          <Header />

          {children}
        </body>
      </Providers>
    </html>
  );
}
